# hello-canary.yaml (Canary 50/50 재시도)
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    # v2(새 버전)의 정의
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Version 2"

  traffic:
    # 50%의 트래픽은 최신 버전(v2)으로 보냅니다.
    - percent: 50
      latestRevision: true

    # 50%의 트래픽은 v1 리비전으로 보냅니다.
    - percent: 50
      revisionName: helloworld-go-00001 # # v1 배포 후 생성된 정확한 리비전 이름입니다.
      latestRevision: false
